title: Haiou Mao's Homepage
page-top-title: Haiou Mao 毛海欧
top-section-bg-text: International Economics
home-subtitle: Haiou Mao&ensp;|&ensp;毛海欧
copyright-text: '&copy; Haiou Mao 2026-2029. All Rights Reserved.'
